services:
  # ローカルで動作するS3互換のオブジェクトストレージ
  minio:
    image: minio/minio
    volumes:
      # - "./minio/data:/data:delegated"
      - minio-store:/data
    ports:
      - ${MINIO_API_HOST_PORT}:${MINIO_API_CONTAINER_PORT}
      - ${MINIO_CONSOLE_HOST_PORT}:${MINIO_CONSOLE_CONTAINER_PORT}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_ADDRESS=${MINIO_SERVER_ADDRESS}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    command: server /data --console-address :${MINIO_CONSOLE_HOST_PORT}
  # MinIOのクライアント
  mc:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - MINIO_API_CONTAINER_PORT=${MINIO_API_CONTAINER_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_ADDRESS=${MINIO_SERVER_ADDRESS}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    # MinIOにバケットを作成するためのコマンドを実行
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:$$MINIO_API_CONTAINER_PORT $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/$$MINIO_BUCKET_NAME;
      /usr/bin/mc anonymous set none myminio/$$MINIO_BUCKET_NAME;
      exit 0;
      "

volumes:
  minio-store:
